IF OBJECT_ID('dbo.Hardware', 'U') IS NULL
CREATE TABLE Hardware
(
    id INT IDENTITY PRIMARY KEY,
    sifra VARCHAR(50) NOT NULL,
    naziv VARCHAR(255) NOT NULL,
    cijena DECIMAL(10,2) NOT NULL,
    tip VARCHAR(50) NOT NULL,
    kolicina INT NOT NULL
);

IF OBJECT_ID('dbo.Category', 'U') IS NULL
CREATE TABLE Category
(
    ID INT IDENTITY PRIMARY KEY,
    TIP VARCHAR(50)
);