spring.application.name=vjezba2
server.port=8082
spring.datasource.url=jdbc:sqlserver://localhost:55242;trustServerCertificate=true;encrypt=true;integratedSecurity=false;databaseName=JavaAdv;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=hardware
spring.datasource.password=hardware
spring.sql.init.mode=always

